version: '3'

services:
  web:
    build: .
    ports:
      - "4040:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - redBase

  db:
    ports:
      - "3310:3306"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Usuario
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - redBase
networks:
  redBase: